mac80211: add he support
move to ath-post-bringup.
add he support.
update 001-fix_build.patch to support kernel 5.2
rebase on Aug 8th
rebase on Aug 16

Change-Id: Ie848ec328088dfe3997a3b38addc3506a3d43f8e
Signed-off-by: Miles Hu <milehu@codeaurora.org>

diff --git a/mac80211/patches/001-fix_build.patch b/mac80211/patches/001-fix_build.patch
--- a/mac80211/patches/001-fix_build.patch
+++ b/mac80211/patches/001-fix_build.patch
@@ -27,7 +27,7 @@
  	@set -e ; test -f local-symbols || (						\
  	echo "/--------------"								;\
  	echo "| You shouldn't run make in the backports tree, but only in"		;\
-@@ -60,58 +62,61 @@ mrproper:
+@@ -60,58 +62,62 @@ mrproper:
  	echo "| (that isn't currently running.)"					;\
  	echo "\\--"									;\
  	false)
@@ -88,52 +88,53 @@
 +
 +Kconfig.kernel: $(STAMP_KERNEL_CONFIG) local-symbols
 +	@printf "Generating local configuration database from kernel ..."
-+	@grep -v -f local-symbols $(KERNEL_CONFIG) | grep = | (                        \
-+		while read l ; do                                               \
-+			if [ "$${l:0:7}" != "CONFIG_" ] ; then                  \
-+				continue                                        ;\
-+			fi                                                      ;\
-+			l=$${l:7}                                               ;\
-+			n=$${l%%=*}                                             ;\
-+			v=$${l#*=}                                              ;\
-+			if [ "$$v" = "m" ] ; then                               \
-+				echo config $$n                                 ;\
-+				echo '    tristate'                             ;\
-+			elif [ "$$v" = "y" ] ; then                             \
-+				echo config $$n                                 ;\
-+				echo '    bool'                                 ;\
-+			else                                                    \
-+				continue                                        ;\
-+			fi                                                      ;\
-+			echo "    default $$v"                                  ;\
-+			echo ""                                                 ;\
-+		done                                                            \
++	@grep -v -f local-symbols $(KERNEL_CONFIG) | grep = | (			\
++		while read l ; do						\
++			if [ "$${l:0:7}" != "CONFIG_" ] ; then			\
++				continue					;\
++			fi							;\
++			l=$${l:7}						;\
++			n=$${l%%=*}						;\
++			v=$${l#*=}						;\
++			if [ "$$v" = "m" ] ; then				\
++				echo config $$n					;\
++				echo '    tristate' 				;\
++			elif [ "$$v" = "y" ] ; then				\
++				echo config $$n					;\
++				echo '    bool'					;\
++			else							\
++				continue					;\
++			fi							;\
++			echo "    default $$v"					;\
++			echo ""							;\
++		done								\
 +	) > $@
 +	@echo " done."
 +
 +Kconfig.versions: Kconfig.kernel
-+	@kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) kernelversion |  \
-+		sed 's/^\(\([3-4]\|2\.6\)\.[0-9]\+\).*/\1/;t;d')                    ;\
-+	test "$$kver" != "" || echo "Kernel version parse failed!"              ;\
-+	test "$$kver" != ""                                                     ;\
-+	kvers="$$(seq 14 39 | sed 's/^/2.6./')"                                 ;\
-+	kvers="$$kvers $$(seq 0 99 | sed 's/^/3./')"                            ;\
-+	kvers="$$kvers $$(seq 0 99 | sed 's/^/4./')"                            ;\
-+	print=0                                                                 ;\
-+	for v in $$kvers ; do                                                   \
-+		if [ "$$print" = "1" ] ; then                                   \
-+			echo config KERNEL_$$(echo $$v | tr . _)        ;\
-+			echo "    def_bool y"                                   ;\
-+		fi                                                              ;\
-+		if [ "$$v" = "$$kver" ] ; then print=1 ; fi                     ;\
++	@kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) kernelversion |	\
++		sed 's/^\(\([3-5]\|2\.6\)\.[0-9]\+\).*/\1/;t;d')		;\
++	test "$$kver" != "" || echo "Kernel version parse failed!"		;\
++	test "$$kver" != ""							;\
++	kvers="$$(seq 14 39 | sed 's/^/2.6./')"					;\
++	kvers="$$kvers $$(seq 0 19 | sed 's/^/3./')"				;\
++	kvers="$$kvers $$(seq 0 20 | sed 's/^/4./')"				;\
++	kvers="$$kvers $$(seq 0 99 | sed 's/^/5./')"				;\
++	print=0									;\
++	for v in $$kvers ; do							\
++		if [ "$$print" = "1" ] ; then					\
++			echo config KERNEL_$$(echo $$v | tr . _)	;\
++			echo "    def_bool y"					;\
++		fi								;\
++		if [ "$$v" = "$$kver" ] ; then print=1 ; fi			;\
 +	done > $@
-+	@RHEL_MAJOR=$$(grep '^RHEL_MAJOR' $(KERNEL_MAKEFILE) |                  \
-+				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')               ;\
-+	RHEL_MINOR=$$(grep '^RHEL_MINOR' $(KERNEL_MAKEFILE) |                   \
-+				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')               ;\
-+	for v in $$(seq 0 $$RHEL_MINOR) ; do                                    \
-+		echo config BACKPORT_RHEL_KERNEL_$${RHEL_MAJOR}_$$v             ;\
-+		echo "    def_bool y"                                           ;\
++	@RHEL_MAJOR=$$(grep '^RHEL_MAJOR' $(KERNEL_MAKEFILE) | 			\
++				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')		;\
++	RHEL_MINOR=$$(grep '^RHEL_MINOR' $(KERNEL_MAKEFILE) | 			\
++				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')		;\
++	for v in $$(seq 0 $$RHEL_MINOR) ; do 					\
++		echo config BACKPORT_RHEL_KERNEL_$${RHEL_MAJOR}_$$v		;\
++		echo "    def_bool y"						;\
 +	done >> $@
 +
 +.DEFAULT:
